# Site settings
title: Armon Sana
description: Forsan et haec olim meminisse juvabit
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "asanayei.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
logo: '/assets/img/logo.svg'
# User settings
username: armon 
user_description: Did someone say tacos?
user_title: bloop
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
